//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheaterInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRequisites
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserRequisites()
        {
            this.UseRequisitiesCostumes = new HashSet<UseRequisitiesCostumes>();
        }
    
        public int RequisitId { get; set; }
        public string RequisitName { get; set; }
        public Nullable<int> UserID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UseRequisitiesCostumes> UseRequisitiesCostumes { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
