//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheaterInventory
{
    using System;
    using System.Collections.Generic;
    
    public partial class UseRequisitiesCostumes
    {
        public int id { get; set; }
        public Nullable<int> RequsitId { get; set; }
        public Nullable<int> CostumeId { get; set; }
        public Nullable<int> UserId { get; set; }
    
        public virtual UserCostumes UserCostumes { get; set; }
        public virtual UserRequisites UserRequisites { get; set; }
        public virtual UserInfo UserInfo { get; set; }
    }
}
